### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bestlem** [wangfenjin/vertical-tabs-safari-extension#3]
It just adds a screen panel saying Verticle tabs and under it a search tabs here and then a + sign

Hit the plus sign and you get a new tab with no vertical tabs pane jusr acting like normal safari tabs.
 Well maybe sometimes after turning other extensions (ghostery off) but even then

Choose from favourites and all your tabs are lost.

**Comment by wangfenjin** [comment]
hi @bestlem  it’s because these pages are protected by safari, we can’t inject any code into that page.

Can do nothing about it.

**Comment by bestlem** [comment]
The problem is that I usually use favourites and that blows away everything and makes it unusable

**Comment by wangfenjin** [comment]
Could you show a screenshot to me? Thanks

**Comment by bestlem** [comment]
https://user-images.githubusercontent.com/37385/118998123-176ef700-b981-11eb-977d-a65f86f35c92.mov

**Comment by bestlem** [comment]
It seems to be OK now - so must be a certain page etc. So close this for now - if I see it again I will reopen
